//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PlayBox.rc
//

#define IDR_RT_MANIFEST1                1
#define IDC_BTN_CLSOE                   2
#define IDR_MENU_TRAY                   3
#define IDD_PLAYBOX_DIALOG              5
#define IDC_TOPPANEL_HOLD               7
#define ID_MEMU_SETTING                 8
#define ID_MEMU_MAIN_PAGE               9
#define ID_MEMU_PROBLEM_REPORT          10
#define IDD_DLG_MINOREXIT               11
#define IDD_MSG_DLG                     12
#define IDD_HOST                        13
#define ID_MENU_SKIN_APPLY              14
#define ID_MENU_SKIN_DELETE             15
#define ID_MENU_MORE_SKIN               16
#define ID_WND_GAMEPLAYING              17
#define ID_WND_GAMERIGHT                18
#define ID_WND_GAMEBOTTOM               19
#define IDC_BTN_REPLAY                  20
#define IDC_BTN_FULL_SCREEN             21
#define ID_GAME_BOTTOM_LOADING_FLASH    22
#define ID_GAME_RIGHT_LOADING_FLASH     23
#define ID_WND_GAME_DOWN_PERCENT        24
#define ID_WND_GAME_SWF                 25
#define ID_WND_QQ_VIEW                  26
#define ID_TREE_QQ                      27
#define ID_WND_MYGAME_VIEW              28
#define IDC_BTN_MUTE                    29
#define IDR_MAINFRAME                   30
#define IDC_BTN_MUTED                   31
#define IDR_MENU1                       32
#define IDC_BTN_EXIT_FULL_SCREEN        33
#define IDC_BTN_GAMERIGHT               34
#define IDC_BTN_GAMERIGHT_CLOSE         35
#define IDB_FRAME_LINE                  36
#define IDC_BTN_GAMERIGHT_OPEN          37
#define IDR_MENU2                       38
#define IDC_BTN_UN_MUTE                 39
#define ID_WND_DOWN_QQ_VIEW             40
#define IDD_DIALOG1                     41
#define ID_BTN_DOWN_TO_MY_GAME          42
#define IDD_TRANS_DLG                   43
#define ID_OPEN                         44
#define ID_SHOW_HIDE_MAIN_WND           45
#define IDC_CURSOR2                     46
#define ID_APP_FORUM                    47
#define IDD_DIALOG2                     48
#define ID_EXIT                         49
#define IDR_MENU_COVERLIST              50
#define IDC_LIST                        51
#define IDC_EDIT_DLG_REG_USERNAME       52
#define IDD_CONFIG                      53
#define IDC_EDIT_DLG_REG_PWD            54
#define IDC_EDIT_DLG_REG_PWD_CHECK      55
#define IDC_CURSOR1                     56
#define IDC_CHECK_DLG_REG_AGREEMENT     57
#define IDR_MENU_LOCALGAME              58
#define IDC_STATIC_RESULT               59
#define IDC_STATIC1                     60
#define IDC_STATIC2                     61
#define IDC_STATIC3                     62
#define IDC_STATIC4                     63
#define IDC_STATIC5                     64
#define IDC_STATIC11                    65
#define IDC_STATIC12                    66
#define IDC_TITLE                       67
#define IDC_STATIC_DLG_REG_MOREINFO     68
#define IDC_STATIC_DLG_REG_AGREEMENT_CONTENT 69
#define IDC_BUTTON_DLG_USERFACE_BROWSER 70
#define IDC_BUTTON_DLG_USERFACE_UPLOAD  71
#define IDC_EDIT_DLG_USERFACE_PATH      72
#define IDC_BTN_CLOSE                   73
#define IDC_STATUS                      74
#define IDC_STATIC10                    75
#define IDC_EDIT_ACCOUNT                76
#define IDC_EDIT_PASSWORD               77
#define IDC_CHECK_REM_PSW               78
#define IDC_CHECK_AUTO_LOG              79
#define IDC_STATIC_ACCOUNT              80
#define IDC_STATIC_PASSWORD1            81
#define IDC_STATIC_REG2                 82
#define IDC_STATIC_FORGET_PASSWORD      83
#define IDC_STATIC_REG                  84
#define IDC_STATIC_TITLE                85
#define IDC_BUTTON_LOG                  86
#define IDC_BUTTON_CANCEL               87
#define IDR_MENU_TITLE                  88
#define ID_MEMU_LOGON_IN                89
#define IDR_MENU_TITLE1                 90
#define IDR_MENU_TRAYICON               91
#define ID_MEMU_LOGON_OUT               92
#define ID_MEMU_CHANGE_SKIN             93
#define ID_MEMU_HELP_ABOUT              94
#define IDM_CHECK_NEW_VERSION           95
#define IDC_STATIC_TEXT_MSG             96
#define IDC_STATIC_LINK_TO_NEW          97
#define IDC_BUTTON_APPLY                98
#define IDD_DLG_CLEANCHACHE             147
#define IDB_BMP_LOADING1                148
#define IDB_BMP_LOADING2                149
#define IDB_BMP_LOADING3                150
#define IDB_BMP_LOADING4                151
#define IDB_BMP_LOADING5                152
#define IDB_BMP_LOADING6                153
#define IDB_BMP_LOADING7                154
#define IDB_BMP_LOADING8                155
#define IDD_DIALOG_ESCTEXT              156
#define IDD_DIALOG_ESCFULLSCR           157
#define IDD_DIALOG3                     158
#define IDD_DLG_FAV_URL                 158
#define IDD_DIALOG4                     159
#define IDD_DIALOG_CHKUPDATE            159
#define IDD_DIALOG5                     160
#define IDI_ICON1                       163
#define IDI_BEAR                        163
#define IDI_ICON2                       164
#define IDI_ICON_BEAR                   164
#define IDC_CONFIG_BTN_DEFAULT          190
#define IDC_CONFIG_LIST                 191
#define IDC_STATIC_PROBLEM              192
#define IDC_STATIC_MAIN_PAGE            193
#define IDC_STATIC_ABOUT_1              194
#define IDC_STATIC_ABOUT_2              195
#define IDC_STATIC_ABOUT_3              196
#define IDC_MP                          197
#define IDC_LP                          198
#define IDC_MP_TEXT                     199
#define IDC_LP_TEXT                     200
#define IDD_DIALOG_DOWN                 203
#define IDD_DIALOG_SYS                  204
#define IDC_GROUP_MIN                   205
#define IDC_CHECK_AUTORUN               206
#define IDC_GROUP_START                 207
#define IDC_STATIC_MINOREXIT            208
#define IDC_RAD_MIN                     209
#define IDC_RAD_EXIT                    210
#define IDC_CHK_NOASK                   211
#define ID_WND_WEBGAME                  212
#define IDC_CHK_IS_SCAN_LOCAL_GAME      212
#define ID_WND_WEBGAMEPLAYING           214
#define IDD_DLG_UPDATE_TIP              215
#define IDC_STATIC_UPDATE_INFO          216
#define IDC_EDIT_UPDATE_INFO            217
#define ID_BTN_LOGO                     218
#define ID_WND_AD_PANEL                 219
#define IDC_OtherReason                 221
#define IDC_MODIFY_ERROR1               222
#define IDC_MODIFY_ERROR2               223
#define IDC_MODIFY_ERROR3               224
#define IDC_MODIFY_ERROR4               225
#define IDC_MODIFY_ERROR5               226
#define IDC_MODIFY_ERROR6               227
#define IDC_MODIFY_ERROR7               228
#define IDC_EDIT_CHECK_WORDS            229
#define IDC_STATIC_CHECK_WORDS          230
#define IDC_STATIC_CHECK_TIP            231
#define ID_BTN_BUG_REPORT               232
#define IDC_COMBO_EXEDOWN               233
#define ID_START                        235
#define ID_PAUSE                        236
#define ID_DELETE                       237
#define ID_START_ALL                    238
#define ID_PAUSE_ALL                    239
#define ID_SELECT_ALL                   240
#define ID_DOWN_SETTINGS                241
#define ID_BTN_DOWNSTART                242
#define ID_BTN_DOWNPAUSE                243
#define ID_BTN_DELETE                   244
#define ID_BTN_OPENDIR                  245
#define ID_STATIC_DOWN_TITLE            246
#define ID_DOWN_LIST_CTRL               247
#define IDC_CHECK_NOASK                 248
#define ID_DOWNLOADINFOTIPS             249
#define IDC_BTN_GAMEINFO_CLOSE          250
#define IDC_BTN_GAMEINFO_OPEN           251
#define IDC_BTN_PAUSE                   252
#define IDC_EDIT1                       253
#define IDC_BUTTON1                     254
#define IDC_GROUP_DOWN1                 255
#define IDC_EMAIL                       256
#define IDC_BTN_BRO_SAVE_PATH           257
#define IDC_EDIT_NUMBER_DOWN            258
#define IDC_EDIT_SAVE_PATH              259
#define IDC_CHK_IS_POPUP_DIALOG_BOX     260
#define IDC_STATIC_PIC_SAVE_PATH        261
#define IDC_STATIC_SAVE_PATTH           262
#define IDC_STATIC_HOTKEY               263
#define IDC_CHK_BOSSKEY                 264
#define IDC_HOTKEY1                     265
#define IDC_HOTKEY_BOSSKEY              266
#define ID_CL_LARGEICON                 267
#define ID_CL_MIDICON                   268
#define ID_CL_SMALLICON                 269
#define ID_CL_DELFROMDISK               270
#define ID_Menu                         271
#define ID_MENU_AUTOADDLOCALGAME        272
#define IDD_HTML_VIEW                   274
#define ID_WND_FLASHGAME_RIGHT          275
#define ID_WND_FLASHGAME_BOTTOM         276
#define IDC_BTN_BROWSER_BACK            277
#define IDC_BTN_BROWSER_FORWARD         278
#define IDC_BTN_BROWSER_REFRESH         279
#define IDC_BTN_BROWSER_FAV             280
#define IDC_BTN_BROWSER_ADDRESS_BAR     281
#define IDC_BROWSER_WEB                 282
#define IDC_BTN_CUT                     283
#define IDC_STATIC_RECT                 284
#define IDC_BTN_WEBGAME_REFRESH         285
#define IDC_BTN_WEBGAME_TO_FULL         286
#define IDC_BTN_WEBGAME_EXIT_FULL       287
#define IDC_BTN_WEBGAME_MUTE            288
#define IDC_BTN_WEBGAME_UNMUTE          289
#define IDC_BTN_WEBGAME_CLEAR_CACHE     290
#define IDC_BTN_WEBGAME_SITE            291
#define IDC_BTN_WEBGAME_CUSTOM_SERVICE  292
#define IDC_BTN_WEBGAME_PAY             293
#define ID_MENU_WEB_GAME_CUSTOM_SERVICE 296
#define ID_CHECK_UPDATE                 297
#define IDD_DLG_ABOUT                   298
#define ID_BTN_ABOUT_OK                 299
#define IDD_DIALOG_CHECK_NEW_VER		300
#define IDC_STATIC_BMP_LOADING			301
#define IDC_BTN_GAMECENTER_MAIN_PAGE	302
#define IDC_BTN_GAMECENTER_FLASHGAME	303
#define IDC_BTN_GAMECENTER_WEBGAME		304
#define IDC_BTN_GAMECENTER_SEARCH		305
#define IDC_EDIT_GAMECENTER_SEARCH		306
#define IDC_WND_GAMECENTER_BROWSER		307
#define ID_BTN_PLAYED_GAME_TIME_ORDER	308
#define ID_BTN_PLAYED_GAME_TO_WEB_GAME	309
#define ID_BTN_PLAYED_GAME_TO_FLASH_GAME	310
#define ID_BTN_PLAYED_GAME_TO_DOWNLOAD_MANAGER	311
#define ID_BTN_PLAYED_GAME_TO_COLLECTED_GAME	312
#define ID_BTN_PLAYED_GAME_TO_DELETE	313
#define ID_WND_PLAYED_GAME_LIST			314
#define ID_WND_PLAYED_GAME_RECOMMAND	315
#define ID_WND_USER_LOGED_IN			316
#define ID_WND_USER_LOGED_OUT			317
#define ID_BTN_USER_MAN_LOGIN			318
#define ID_BTN_USER_MAN_REGISTER		319
#define IDC_BTN_CHK_CANCEL				320
#define IDC_BTN_CHK_INSTALL				321
#define IDC_BTN_CHK_DONE				322
#define IDC_BTN_CHK_ISDOWN				323
#define IDC_BTN_CHK_CLOSE				324
#define ID_BNT_WEB_WND_CLOSE			325
#define IDD_DLG_LOGIN					326
#define ID_BTN_LOGIN_CLOSE				327
#define ID_BTN_LOGIN_REG				328
#define ID_BTN_LOGIN_FORGET_PASS		329
#define ID_BTN_REMEMBER_PASS_CHECK		330
#define ID_BTN_REMEMBER_PASS_UNCHECK	331
#define ID_BTN_AUTO_LOGIN_CHECK			332
#define ID_BTN_AUTO_LOGIN_UNCHECK		333
#define ID_BTN_LOGIN_LOGIN				334
#define ID_BTN_LOGIN_CANCEL				335
#define IDC_EDIT_LOGIN_PASS_WORD		336
#define IDC_EDIT_LOGIN_USER_NAME		337
#define ID_BTN_ABOUT_CLOSE				338
#define IDC_BTN_CLOSETAB				339
#define ID_STATIC_LOGIN_ERR				340
#define ID_STATIC_LOGEDOUT_LOGIN_ERR	341
#define ID_BTN_USER_MAN_LOGOUT			342
#define ID_BTN_GO_TO_GAME_CENTER		343
#define ID_WND_PLAYED_GAME_WELCOME		344
#define ID_STATIC_BOTTOM_PANEL_WEB_GAME1	345
#define ID_STATIC_BOTTOM_PANEL_WEB_GAME2	346
#define ID_FLASH_GAME_CTRL_PANEL		347
#define ID_FLASH_GAME_CENTER_PANEL		348

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        165
#define _APS_NEXT_COMMAND_VALUE         32797
#define _APS_NEXT_CONTROL_VALUE         1019
#define _APS_NEXT_SYMED_VALUE           140
#endif
#endif
