//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PlayBox.rc
//
#define IDR_RT_MANIFEST1                1
#define IDC_BTN_CLSOE                   2
#define IDR_MENU_TRAY                   4
#define MSG_SHOW_TRAYICONBALLOON        101
#define IDD_PLAYBOX_DIALOG              102
#define MSG_DELETE_TRAY                 102
#define IDC_TOPPANEL_HOLD               103
#define ID_MEMU_SETTING                 104
#define ID_MEMU_MAIN_PAGE               105
#define ID_MEMU_PROBLEM_REPORT          106
#define IDD_DLG_MINOREXIT               107
#define IDD_MSG_DLG                     108
#define IDD_HOST                        109
#define ID_MENU_SKIN_APPLY              110
#define ID_MENU_SKIN_DELETE             111
#define ID_MENU_MORE_SKIN               112
#define ID_WND_GAMEPLAYING              115
#define ID_WND_GAMERIGHT                116
#define ID_WND_GAMEBOTTOM               117
#define IDC_BTN_REPLAY                  118
#define IDC_BTN_FULL_SCREEN             119
#define ID_GAME_BOTTOM_LOADING_FLASH    120
#define ID_GAME_RIGHT_LOADING_FLASH     121
#define ID_WND_GAME_DOWN_PERCENT        122
#define ID_WND_GAME_SWF                 123
#define ID_WND_QQ_VIEW                  124
#define ID_TREE_QQ                      125
#define ID_WND_MYGAME_VIEW              126
#define IDC_BTN_MUTE                    127
#define IDR_MAINFRAME                   128
#define IDC_BTN_MUTED                   128
#define IDR_MENU1                       129
#define IDC_BTN_EXIT_FULL_SCREEN        129
#define IDC_BTN_GAMERIGHT               130
#define IDC_BTN_GAMERIGHT_CLOSE         131
#define IDB_FRAME_LINE                  132
#define IDC_BTN_GAMERIGHT_OPEN          132
#define IDR_MENU2                       133
#define IDC_BTN_UN_MUTE                 133
#define ID_WND_DOWN_QQ_VIEW             134
#define IDD_DIALOG1                     135
#define ID_BTN_DOWN_TO_MY_GAME          135
#define IDD_TRANS_DLG                   136
#define ID_OPEN                         137
#define ID_WND_GAME_CTRL                137
#define ID_SHOW_HIDE_MAIN_WND           138
#define IDC_CURSOR2                     138
#define IDC_BTN_SWITCH                  138
#define ID_APP_FORUM                    139
#define IDD_DIALOG2                     139
#define ID_WND_GAME_INFO                139
#define ID_EXIT                         140
#define IDR_MENU_COVERLIST              140
#define IDC_LIST                        141
#define IDC_EDIT_DLG_REG_USERNAME       142
#define IDD_CONFIG                      142
#define IDC_EDIT_DLG_REG_PWD            143
#define IDC_EDIT_DLG_REG_PWD_CHECK      144
#define IDC_CURSOR1                     144
#define IDC_CHECK_DLG_REG_AGREEMENT     145
#define IDR_MENU_LOCALGAME              146
#define IDC_STATIC_RESULT               149
#define IDC_STATIC1                     150
#define IDC_STATIC2                     151
#define IDC_STATIC3                     152
#define IDC_STATIC4                     153
#define IDC_STATIC5                     154
#define IDC_STATIC11                    155
#define IDC_STATIC12                    156
#define IDC_TITLE                       157
#define IDC_STATIC_DLG_REG_MOREINFO     158
#define IDC_STATIC_DLG_REG_AGREEMENT_CONTENT 159
#define IDC_BUTTON_DLG_USERFACE_BROWSER 161
#define IDC_BUTTON_DLG_USERFACE_UPLOAD  162
#define IDC_EDIT_DLG_USERFACE_PATH      163
#define IDC_BTN_CLOSE                   164
#define IDC_STATUS                      165
#define IDC_STATIC10                    166
#define IDC_EDIT_ACCOUNT                168
#define IDC_EDIT_PASSWORD               169
#define IDC_CHECK_REM_PSW               170
#define IDC_CHECK_AUTO_LOG              171
#define IDC_STATIC_ACCOUNT              172
#define IDC_STATIC_PASSWORD1            173
#define IDC_STATIC_REG2                 174
#define IDC_STATIC_FORGET_PASSWORD      175
#define IDC_STATIC_REG                  176
#define IDC_STATIC_TITLE                177
#define IDC_BUTTON_LOG                  178
#define IDC_BUTTON_CANCEL               179
#define IDR_MENU_TITLE                  180
#define ID_MEMU_LOGON_IN                181
#define IDR_MENU_TITLE1                 181
#define IDR_MENU_TRAYICON               181
#define ID_MEMU_LOGON_OUT               182
#define ID_MEMU_CHANGE_SKIN             183
#define ID_MEMU_HELP_ABOUT              184
#define IDM_CHECK_NEW_VERSION           185
#define IDC_STATIC_TEXT_MSG             186
#define IDC_STATIC_LINK_TO_NEW          187
#define IDC_BUTTON_APPLY                189
#define IDC_CONFIG_BTN_DEFAULT          190
#define IDC_CONFIG_LIST                 191
#define IDC_STATIC_PROBLEM              192
#define IDC_STATIC_MAIN_PAGE            193
#define IDC_STATIC_ABOUT_1              194
#define IDC_STATIC_ABOUT_2              195
#define IDC_STATIC_ABOUT_3              196
#define IDC_MP                          197
#define IDC_LP                          198
#define IDC_MP_TEXT                     199
#define IDC_LP_TEXT                     200
#define IDD_DIALOG_DOWN                 203
#define IDD_DIALOG_SYS                  204
#define IDC_GROUP_MIN                   205
#define IDC_CHECK_AUTORUN               206
#define IDC_GROUP_START                 207
#define IDC_STATIC_MINOREXIT            208
#define IDC_RAD_MIN                     209
#define IDC_RAD_EXIT                    210
#define IDC_CHK_NOASK                   211
#define ID_WND_WEBGAME                  212
#define IDC_CHK_IS_SCAN_LOCAL_GAME      212
#define ID_WND_WEBGAMERIGHT             213
#define ID_WND_WEBGAMEPLAYING           214
#define IDD_DLG_UPDATE_TIP              215
#define IDC_STATIC_UPDATE_INFO          216
#define IDC_EDIT_UPDATE_INFO            217
#define ID_BTN_LOGO                     218
#define ID_WND_AD_PANEL                 219
#define IDC_OtherReason                 221
#define IDC_MODIFY_ERROR1               222
#define IDC_MODIFY_ERROR2               223
#define IDC_MODIFY_ERROR3               224
#define IDC_MODIFY_ERROR4               225
#define IDC_MODIFY_ERROR5               226
#define IDC_MODIFY_ERROR6               227
#define IDC_MODIFY_ERROR7               228
#define IDC_EDIT_CHECK_WORDS            229
#define IDC_STATIC_CHECK_WORDS          230
#define IDC_STATIC_CHECK_TIP            231
#define ID_BTN_BUG_REPORT               232
#define IDC_COMBO_EXEDOWN               233
#define ID_START                        235
#define ID_PAUSE                        236
#define ID_DELETE                       237
#define ID_START_ALL                    238
#define ID_PAUSE_ALL                    239
#define ID_SELECT_ALL                   240
#define ID_DOWN_SETTINGS                241
#define ID_BTN_DOWNSTART                242
#define ID_BTN_DOWNPAUSE                243
#define ID_BTN_DELETE                   244
#define ID_BTN_OPENDIR                  245
#define ID_STATIC_DOWN_TITLE            246
#define ID_DOWN_LIST_CTRL               247
#define IDC_CHECK_NOASK                 248
#define ID_DOWNLOADINFOTIPS             249
#define IDC_BTN_GAMEINFO_CLOSE          250
#define IDC_BTN_GAMEINFO_OPEN           251
#define IDC_BTN_CUT                     252
#define IDC_EDIT1                       1001
#define IDC_BUTTON1                     1002
#define IDC_GROUP_DOWN1                 1003
#define IDC_EMAIL                       1004
#define IDC_BTN_BRO_SAVE_PATH           1004
#define IDC_EDIT_NUMBER_DOWN            1009
#define IDC_EDIT_SAVE_PATH              1010
#define IDC_CHK_IS_POPUP_DIALOG_BOX     1011
#define IDC_STATIC_PIC_SAVE_PATH        1012
#define IDC_STATIC_SAVE_PATTH           1013
#define IDC_STATIC_HOTKEY               1014
#define IDC_CHK_BOSSKEY                 1015
#define IDC_HOTKEY1                     1016
#define IDC_HOTKEY_BOSSKEY              1016
#define ID_CL_LARGEICON                 32772
#define ID_CL_MIDICON                   32774
#define ID_CL_SMALLICON                 32776
#define ID_CL_DELFROMDISK               32778
#define ID_Menu                         32779
#define ID_MENU_AUTOADDLOCALGAME        32781
#define ID_MENU_MANUALADDLOCALGAME      32783
#define IDD_HTML_VIEW						158

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1017
#define _APS_NEXT_SYMED_VALUE           140
#endif
#endif
