#ifndef _CONFIG_SETTING_DEF_H
#define _CONFIG_SETTING_DEF_H

#include "AfxConfigType.h"

static const char* CONF_SETTING_MODULE_NAME				= "Setting";

static const char* CONF_SETTING_SKIN_IDX				= "skin";
//官方网站，在设置下拉框里
static const char* CONF_SETTING_CONFIG_MAIN_PAGE		= "MainPage";	
//客服，问题反馈，所有游戏一个客服
static const char* CONF_SETTING_CONFIG_WEB_GAME_CUSTOM_SERVICE	= "WebGameCustomService";
//网游支付，后面要加ID
static const char* CONF_SETTING_CONFIG_PAY				= "PayUrl";
//网游服务器，后面要加ID,svrid,username,pass
//http://box.najiuwan.com/index.php?s=/game/login_game_box/username/yinshaohua/pass/1111/flag/asdasd23432fdsfdsf/id/107/svrid/2
static const char* CONF_SETTING_CONFIG_WEB_GAME_URL		= "WebGameUrl";
//网游官网，后面要加ID
static const char* CONF_SETTING_CONFIG_WEB_GAME_OFFICE_SITE		= "WebGameOfficeSite";
//游戏中心首页
static const char* CONF_SETTING_CONFIG_GAME_CENTER_MAIN_PAGE_URL = "GameCenterMainPage";
static const char* CONF_SETTING_CONFIG_GAME_CENTER_FLASH_GAME_URL = "GameCenterFlashGame";
static const char* CONF_SETTING_CONFIG_GAME_CENTER_WEB_GAME_URL	= "GameCenterWebGame";
static const char* CONF_SETTING_CONFIG_GAME_CENTER_SEARCH_URL	= "GameCenterSearch";
//小游戏下载页广告url
static const char* CONF_SETTING_CONFIG_FLASH_DOWN_AD_URL	= "FlashDownAdUrl";
//游戏资讯首页
static const char* CONF_SETTING_CONFIG_GAME_INFO_HOME_URL = "GameInfoMainPage";
//小游戏右侧网页，后面加id
static const char* CONF_SETTING_CONFIG_FLASH_GAME_RIGHT_URL = "FlashGameRightUrl";
//小游戏播放页面下方网页
static const char* CONF_SETTING_CONFIG_FLASH_GAME_BOTTOM_URL = "FlashGameBottomUrl";
//玩过的小游戏 右侧 今日推荐
static const char* CONF_SETTING_CONFIG_PLAYED_GAME_RIGHT_URL = "PlayedGameRightUrl";
//用户登录server
static const char* CONF_SETTING_CONFIG_USER_SVR = "UserSvr";
//用户收藏，玩过，删除游戏的server
static const char* CONF_SETTING_CONFIG_COLLECTE_GAME_ACTION_REPORT_URL = "CollectGameActionReportUrl";

static const char* CONF_SETTING_CONFIG_IFASKEXIT		= "askexit";
static const char* CONF_SETTING_CONFIG_EXITCHOICE		= "exitchoice";
static const char* CONF_SETTING_LOGIN_USER_NAME			= "UN";
static const char* CONF_SETTING_LOGIN_PASSWORD			= "PW";
static const char* CONF_SETTING_COLOR					= "ChangeColorValue";
static const char* CONF_SETTING_LIGHT					= "changeColorLight";
static const char* CONF_SETTING_COLOR_BTN_INDEX			= "ColorIndex";
static const char* CONF_SETTING_COLOR_USER				= "ColorUser";
static const char* CONF_SETTING_FIRST_TIME_CHANGESKIN	= "FirstTimeChangeSkin";

static const char* CONF_SETTING_ENABLE_BOSS_KEY			= "UseBossKey";
static const char* CONF_SETTING_BOSS_KEY_VALUE			= "BossKeyValue";
static const char* CONF_SETTING_AUTO_LOGIN				= "AutoLogin";
static const char* CONF_SETTING_REMEMBER_PASSWORD		= "RememberPassword";

static const char* CONF_SETTING[] =
{
	CONF_SETTING_SKIN_IDX,				TYPE_CONFIG_STR,
	CONF_SETTING_CONFIG_MAIN_PAGE,		TYPE_CONFIG_STR,
	CONF_SETTING_CONFIG_WEB_GAME_CUSTOM_SERVICE,	TYPE_CONFIG_STR,
	CONF_SETTING_CONFIG_PAY,			TYPE_CONFIG_STR,
	CONF_SETTING_CONFIG_WEB_GAME_URL,	TYPE_CONFIG_STR,
	CONF_SETTING_CONFIG_WEB_GAME_OFFICE_SITE, TYPE_CONFIG_STR,
	CONF_SETTING_CONFIG_GAME_CENTER_MAIN_PAGE_URL, TYPE_CONFIG_STR,
	CONF_SETTING_CONFIG_GAME_CENTER_FLASH_GAME_URL, TYPE_CONFIG_STR,
	CONF_SETTING_CONFIG_GAME_CENTER_WEB_GAME_URL, TYPE_CONFIG_STR,
	CONF_SETTING_CONFIG_GAME_CENTER_SEARCH_URL, TYPE_CONFIG_STR,
	CONF_SETTING_CONFIG_FLASH_DOWN_AD_URL,	TYPE_CONFIG_STR,
	CONF_SETTING_CONFIG_GAME_INFO_HOME_URL,	TYPE_CONFIG_STR,
	CONF_SETTING_CONFIG_FLASH_GAME_RIGHT_URL,	 TYPE_CONFIG_STR,
	CONF_SETTING_CONFIG_FLASH_GAME_BOTTOM_URL,	TYPE_CONFIG_STR,
	CONF_SETTING_CONFIG_PLAYED_GAME_RIGHT_URL,  	TYPE_CONFIG_STR,
	CONF_SETTING_CONFIG_USER_SVR,	TYPE_CONFIG_STR,
	CONF_SETTING_CONFIG_COLLECTE_GAME_ACTION_REPORT_URL, TYPE_CONFIG_STR,
	
	CONF_SETTING_CONFIG_IFASKEXIT,		TYPE_CONFIG_BOOL,
	CONF_SETTING_CONFIG_EXITCHOICE,		TYPE_CONFIG_BOOL,
	CONF_SETTING_LOGIN_USER_NAME,		TYPE_CONFIG_STR,
	CONF_SETTING_LOGIN_PASSWORD,		TYPE_CONFIG_STR,
	CONF_SETTING_COLOR,					TYPE_CONFIG_INT,
	CONF_SETTING_LIGHT,					TYPE_CONFIG_INT,
	CONF_SETTING_COLOR_BTN_INDEX,		TYPE_CONFIG_INT,
	CONF_SETTING_COLOR_USER,			TYPE_CONFIG_INT,
	CONF_SETTING_FIRST_TIME_CHANGESKIN, TYPE_CONFIG_BOOL,
	CONF_SETTING_ENABLE_BOSS_KEY,		TYPE_CONFIG_BOOL,
	CONF_SETTING_BOSS_KEY_VALUE,		TYPE_CONFIG_INT,
	CONF_SETTING_AUTO_LOGIN,			TYPE_CONFIG_BOOL,
	CONF_SETTING_REMEMBER_PASSWORD,		TYPE_CONFIG_BOOL
};

#define ID_HOTKEY_BOSSKEY		10086

#if !defined CONF_DLG_CTRL_ID
#define CONF_DLG_CTRL_ID

#define IDC_CONF_CHK_AUTOLOGIN		1000
#define	IDC_CONF_BTN_OK				1001
#define IDC_CONF_BTN_CANCEL			1002
#define IDC_CONF_BTN_RESET			1003
#define IDC_CONF_BTN_CLOSE			1004

#define IDC_CONF_CHK_AUTORUN		1005
#define IDC_CONF_CHK_ENABLE_BOSSKEY	1006
#define IDC_CONF_CHK_PRINTSCREEN	1007
#define IDC_CONF_RAD_MIN			1008
#define IDC_CONF_RAD_EXIT			1009
#define IDC_CONF_CHK_NOASK			1010

#endif // CONF_DLG_CTRL_ID

#endif