#ifndef _GLOBAL_P2P_PRIORITY_H
#define _GLOBAL_P2P_PRIORITY_H

#define P2P_PRIORITY_ZIPRES				7
#define P2P_PRIORITY_SKINRES			5
#define P2P_PRIORITY_HANDLE_SKINRES     10
#define P2P_PRIORITY_CDPICRES			4
#define P2P_PRIORITY_PREFETCH			4
#define P2P_PRIORITY_STARSHOW			6
#define P2P_PRIORITY_DOWN				8
#define P2P_PRIORITY_PLAYING_SONG		10
#define P2P_PRIORITY_PLAYING_MV			10
#define P2P_PRIORITY_AD					9
#define P2P_PRIORITY_KSONG				10
#define P2P_PRIORITY_AUDIOD				10
#define P2P_PRIORITY_PLUGIN				10



#endif