#ifndef _MESSAGE_ID_H
#define _MESSAGE_ID_H


const DWORD		ID_MESSAGE_SEARCH = 1;

const DWORD		ID_MESSAGE_PANEL_CHANGE = 2;

const DWORD		ID_MESSAGE_QQDATA = 3;

const DWORD		ID_MESSAGE_REFRESH = 4;

const DWORD		ID_MESSAGE_APP_EXIT = 5;

const DWORD		ID_MESSAGE_CHECKNETCONNECT = 6;

const DWORD		ID_MESSAGE_USER = 7;

const DWORD		ID_MESSAGE_LAYOUTMGR = 8;

const DWORD		ID_MESSAGE_SKIN_UPDATE = 9;

const DWORD		ID_MESSAGE_CONFUPDATE = 10;

const DWORD		ID_MESSAGE_TABBAR = 11;

const DWORD		ID_MESSAGE_HTTP_DOWN = 12;

const DWORD		ID_MESSAGE_APPEXIT = 13;

const DWORD		ID_MESSAGE_QQ_ITEM_CHANGE = 14;

const DWORD		ID_MESSAGE_AD = 15;

const DWORD		ID_MESSAGE_DOWNDOWN = 16;

const DWORD		ID_MESSAGE_EXE_HTTP_DOWN = 17;

const DWORD		ID_MESSAGE_HILIGHT_MYGAME = 18;

const DWORD		ID_MESSAGE_UPDATE_GAME_TIMES = 19;

#endif