#ifndef _MESSAGE_ID_H
#define _MESSAGE_ID_H

enum 
{
	MSG_START = WM_USER,
	ID_MESSAGE_PANEL_CHANGE,
	ID_MESSAGE_REFRESH,
	ID_MESSAGE_APP_EXIT,
	ID_MESSAGE_CHECKNETCONNECT,
	ID_MESSAGE_USER,
	ID_MESSAGE_LAYOUTMGR,
	ID_MESSAGE_CONFUPDATE,
	ID_MESSAGE_TABBAR,
	ID_MESSAGE_HTTP_DOWN,
	ID_MESSAGE_APPEXIT,
	ID_MESSAGE_AD,
	ID_MESSAGE_EXE_HTTP_DOWN,
	ID_MESSAGE_HILIGHT_MYGAME,
	ID_MESSAGE_UPDATE_GAME_TIMES,
	ID_MESSAGE_SEARCH,
	MSG_SHOW_TRAYICONBALLOON,
	MSG_NEW_BROWSER_WND,
	MSG_DELETE_TRAY,
	WM_MY_TRAY_NOTIFICATION,
	MSG_AFTER_UICREATE,
	MSG_CONF_UPDATE,
	MSG_CHANGE_TEXT_DLG,
	MSG_HTTP_DOWNLOAD,
	MSG_OPEN_REG_DIALOG,
	MSG_DO_TASK,
	ID_MESSAGE_GAMEDATA,
	MSG_OPEN_FORGET_PASS_DIALOG,
};

#endif