#include "MessageID.h"



//search message
KwGUID	ID_MESSAGE_SEARCH(ID_MESSAGE_SEARCH);
KwGUID  ID_MESSAGE_PLAYLIST(ID_MESSAGE_PLAYLIST);
KwGUID	ID_MESSAGE_PLAYSONG(ID_MESSAGE_PLAYSONG);
KwGUID	ID_MESSAGE_PLAYMV(ID_MESSAGE_PLAYMV);
KwGUID	ID_MESSAGE_CURRPLAY(ID_MESSAGE_CURRPLAY);
KwGUID	ID_MESSAGE_DOWNDOWN(ID_MESSAGE_DOWNDOWN);
KwGUID	ID_MESSAGE_DOWNCLASS(ID_MESSAGE_DOWNCLASS);
KwGUID	ID_MESSAGE_P2P_PLAYINGMV(ID_MESSAGE_P2P_PLAYINGMV);
KwGUID	ID_MESSAGE_P2P_PLAYINGSONG(ID_MESSAGE_P2P_PLAYINGSONG);
KwGUID	ID_MESSAGE_LYRIC(ID_MESSAGE_LYRIC);
KwGUID  ID_MESSAGE_PANEL_CHANGE(ID_MESSAGE_PANEL_CHANGE);
KwGUID  ID_MESSAGE_QQDATA(ID_MESSAGE_QQDATA);
KwGUID	ID_MESSAGE_REFRESH(ID_MESSAGE_WEB_REFRESH);
KwGUID	ID_MESSAGE_APPEXIT(ID_MESSAGE_APP_EXIT);
KwGUID	ID_MESSAGE_CHECKNETCONNECT(ID_MESSAGE_CHECKNETCONNECT);
KwGUID	ID_MESSAGE_USER(ID_MESSAGE_USER);
KwGUID	ID_MESSAGE_FLASHHOLDER(ID_MESSAGE_FLASHHOLDER);
KwGUID	ID_MESSAGE_LAYOUTMGR(ID_MESSAGE_LAYOUTMGR);
KwGUID	ID_MESSAGE_CONFUPDATE(ID_MESSAGE_CONFUPDATE);
KwGUID  ID_MESSAGE_SKIN_UPDATE(ID_MESSAGE_SKIN_UPDATE);
KwGUID	ID_MESSAGE_SYNCPLAYLIST(ID_MESSAGE_SYNCPLAYLIST);
