#ifndef _MESSAGE_ID_H
#define _MESSAGE_ID_H

static int g_iMsgIDCounter = 0;
#define MSG_ID(sig) const DWORD sig = g_iMsgIDCounter++;
#define MSG_ID_CONST(i, sig) const DWORD sig = i;

MSG_ID_CONST(0, ID_MESSAGE_SEARCH)
MSG_ID_CONST(1, ID_MESSAGE_PANEL_CHANGE)
MSG_ID_CONST(2, ID_MESSAGE_REFRESH)
MSG_ID_CONST(3, ID_MESSAGE_APP_EXIT)
MSG_ID_CONST(4, ID_MESSAGE_CHECKNETCONNECT)
MSG_ID_CONST(5, ID_MESSAGE_USER)
MSG_ID_CONST(6, ID_MESSAGE_LAYOUTMGR)
MSG_ID_CONST(7, ID_MESSAGE_CONFUPDATE)
MSG_ID_CONST(8, ID_MESSAGE_TABBAR)
MSG_ID_CONST(9, ID_MESSAGE_HTTP_DOWN)
MSG_ID_CONST(10, ID_MESSAGE_APPEXIT)
MSG_ID_CONST(11, ID_MESSAGE_AD)
MSG_ID_CONST(12, ID_MESSAGE_DOWNDOWN)
MSG_ID_CONST(13, ID_MESSAGE_EXE_HTTP_DOWN)
MSG_ID_CONST(14, ID_MESSAGE_HILIGHT_MYGAME)
MSG_ID_CONST(15, ID_MESSAGE_UPDATE_GAME_TIMES)

#undef MSG_ID
#undef MSG_ID_CONST
#endif